services:
  - type: web
    name: healthcare-system-backend
    env: java
    buildCommand: |
      apt-get update && apt-get install -y openjdk-17-jdk
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      chmod +x ./mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/healthcare-system-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 8080
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false 