services:
  - type: web
    name: healthcare-backend
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/HealthCareSystem-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-url.vercel.app 